server:
  port: 8183
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/std-address
    username: root
    password: Farine27@
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true